# Generated by Django 5.0.7 on 2024-07-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rtech", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Launches",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("rocket", models.TextField(blank=True, null=True)),
                ("youtube", models.CharField(max_length=200)),
            ],
        ),
    ]
